### ISSUE TITLE
import vertica_python

### ISSUE THREAD

**Issue by intellectualanarchy** [uber/vertica-python#101]
after installing vertica-python, I encountered the following issue:

`import vertica_python`
  File "C:\Users\user_name\AppData\Local\Continuum\Anaconda3\lib\site-packages\vertica_python-0.5.5-py3.5.egg\vertica_python\vertica\connection.py", line 153
    except Exception, e:
                               ^
SyntaxError: invalid syntax

**Comment by BasilPH** [comment]
What version of Python are you using? vertica-python does (sadly) not yet support Python 3. There is an unmerged pull request that adds support for Python 3: https://github.com/uber/vertica-python/pull/91

**Comment by alexjikim** [comment]
this _should_ be fixed as of version 0.6.1
