### ISSUE TITLE
Python 3 timestamp_tz_parse TypeError

### ISSUE THREAD

**Issue by trianta2** [uber/vertica-python#117]
The following function:
```
def timestamp_tz_parse(s):
    # if timezome is simply UTC...
    if s.endswith('+00'):
        # remove time zone
        ts = timestamp_parse(s[:-3])
        ts = ts.replace(tzinfo=pytz.UTC)
        return ts
    # other wise do a real parse (slower)
    return parser.parse(s)
```
raises `TypeError: endswith first arg must be bytes or a tuple of bytes, not str` at [this line](https://github.com/uber/vertica-python/blob/master/vertica_python/vertica/column.py#L66). 

It appears that `s` is a bytes object, not str. Changing `if s.endswith('+00'):` to `if s.endswith(b'+00'):` resolves the issue for me.

I'm using:
 - Python 3.4.4
 - vertica-python==0.6.2

**Comment by dennisobrien** [comment]
A Vertica `TimestampTz` column gets parsed by `timestamp_tz_parse` while a `Timestamp` column gets parsed by `timestamp_parse`.  The `timestamp_parse` method ends up calling `datetime.strptime` which does require a string.  In this case it might be better to just coerce to strings in these functions.

This code path calls `timestamp_parse`:
```
cursor = connection.cursor()
query = """
select
  to_timestamp('2016-05-15 13:15:17.789', 'YYYY-MM-DD HH:MI:SS.MS')
;
"""
cursor.execute(query)
cursor.fetchall()
```
and throws this exception:
```
/usr/local/lib/python3.5/dist-packages/vertica_python-0.6.2-py3.5.egg/vertica_python/vertica/column.py in _timestamp_parse(s)
     53     if len(s) == 19:
     54         return datetime.strptime(s, '%Y-%m-%d %H:%M:%S')
---> 55     return datetime.strptime(s, '%Y-%m-%d %H:%M:%S.%f')
     56 
     57 

TypeError: strptime() argument 1 must be str, not bytes
```

While this code path calls `timestamp_tz_parse`:
```
query = """
select
  to_timestamp_tz('2016-05-15 13:15:17.789 UTC', 'YYYY-MM-DD HH:MI:SS.MS TZ')
;
"""
cursor.execute(query)
cursor.fetchall()
```
throws this exception
```
/usr/local/lib/python3.5/dist-packages/vertica_python-0.6.2-py3.5.egg/vertica_python/vertica/column.py in timestamp_tz_parse(s)
     64 def timestamp_tz_parse(s):
     65     # if timezome is simply UTC...
---> 66     if s.endswith('+00'):
     67         # remove time zone
     68         ts = timestamp_parse(s[:-3])

TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```
