### ISSUE TITLE
Using ' in json result sequence item 0: expected str instance, dict found

### ISSUE THREAD

**Issue by drno-reg** [uber/vertica-python#167]
Hello,

I have json 

[{'OPERATION_ID': 381, 'NAME': 'Financial data', 'LOCATION': 'Hong Kong', 'TYPE': 'Credit'},{'OPERATION_ID': 382, 'NAME': 'Financial data', 'LOCATION': 'Berlin', 'TYPE': 'Debit'}]

and try insert in Vertica

wrote this code by python

VerticaList = list()
VerticaList.append('{'OPERATION_ID': 381, 'NAME': 'Financial data', 'LOCATION': 'Hong Kong', 'TYPE': 'Credit'}')
VerticaList.append('{'OPERATION_ID': 382, 'NAME': 'Financial data', 'LOCATION': 'Berlin', 'TYPE': 'Debit'}')
connection = vertica_python.connect(**conn_info)
cursor = connection.cursor()
cursor.copy("COPY operations.view FROM STDIN parser fjsonparser() ",''.join(Vertica_List))
connection.commit()
connection.close()

and got error 
sequence item 0: expected str instance, dict found

How resolve this problem?

p.s. 
If I use " instead ' result was ok.

**Comment by feinsteinben** [comment]
`'` is not a valid json quotation mark (according to the json standard). you should `"` instead.
