### ISSUE TITLE
NULL not being inserted

### ISSUE THREAD

**Issue by vkurakundi** [uber/vertica-python#207]
I am trying to run a query against a source Vertica DB, export it into a CSV file using python CSV module; and then using the copy command I want to copy the contents of the CSV file into a destination Vertica DB. The issue I am facing is where ever there is a NULL in the source DB, it is being exported as Python None in the CSV and then when I try to copy it, its being copied as an empty string ' ' , where in I want it to be NULL (not the string NULL, but the Vertica NULL).

**Comment by pachewise** [comment]
This might be due to the python CSV module - you may need to specify that empty string should be NULL: `COPY <your statements here> WITH NULL as ''`

**Comment by vkurakundi** [comment]
@pachewise I used `COPY <statements> WITH NULL as ''` and it worked. I forgot to update/close this issue. Thank you for the reply.
