### ISSUE TITLE
connect() chokes on unicode arguments

### ISSUE THREAD

**Issue by nchammas** [uber/vertica-python#29]
Passing in a dictionary with unicode keys and values to `connect()` yields:
> ConnectionError: argument for 's' must be a string

The stack trace leads back [here](https://github.com/uber/vertica-python/blob/ec2a26ab7956311792720562db2e60c3a34e186b/vertica_python/vertica/connection.py#L136).

I'm not sure how other database modules handle unicode connection parameters, but I think `psycopg2` accepts them. Does it make sense to modify `vertica-python` to accept unicode parameters as well?

You will have unicode connection information if, for example, you are loading it from a file via `json.loads()`. The work-around I'm using is to load the connection information using `ast.literal_eval()`, which gives you a dictionary with ASCII strings.

**Comment by jberka** [comment]
Will look into this one.

**Comment by jberka** [comment]
@alexjikim Also fixed.
