### ISSUE TITLE
Dependency on Unix specific package crypt

### ISSUE THREAD

**Issue by Maksim-Vatkin** [uber/vertica-python#46]
I got the following while trying
from vertica_python import connect

ImportError                               Traceback (most recent call last)
<ipython-input-1-e8ba213fe24f> in <module>()
----> 1 from vertica_python import connect

build\bdist.win32\egg\vertica_python\__init__.py in <module>()

build\bdist.win32\egg\vertica_python\vertica\connection.py in <module>()

build\bdist.win32\egg\vertica_python\vertica\messages\__init__.py in <module>()

build\bdist.win32\egg\vertica_python\vertica\messages\frontend_messages\password.py in <module>()

ImportError: No module named crypt

**Comment by alexjikim** [comment]
I believe this shoud be fixed as of: https://github.com/uber/vertica-python/pull/44
