### ISSUE TITLE
How to iterate rows?

### ISSUE THREAD

**Issue by zer0n** [uber/vertica-python#47]
In the current implementation, is there a way to iterate and process rows without loading all rows in raw form into memory?

**Comment by zer0n** [comment]
Never mind. I didn't read the README carefully.

**Comment by zer0n** [comment]
I've read the README but instantiating the cursor with a handler isn't quite the same. For example, if I want to write a query result to a csv file with header, I need to run the query and write the header first, before iterating rows and calling the handler for each row.

Or am I missing something?

**Comment by alexjikim** [comment]
i think in your case you'll need to write the header to a file prior to issuing a query. the row handler function would contain the logic to append a row to open file. if im understanding your question correctly...

**Comment by zer0n** [comment]
How do we know the header before executing the query?

**Comment by alexjikim** [comment]
ah ok i see the problem now. for a hacky workaround, i would try executing the query with a LIMIT 0 to only get the header information back, then execute again using the handler.

Ill close this issue out, but feel free to open a new one with a more appropriate title regarding not being able to access header info in a streaming query.

**Comment by zer0n** [comment]
Well, my way was using get_one_row() and checking for None, i.e. the same way fetchall() is implemented.

But that's exactly what an iterator is about. By not having an iterator, we encourage users to use fetchall() and then iterate over fetchall(). I have seen so many of that.

**Comment by zer0n** [comment]
Resolved: https://github.com/uber/vertica-python/commit/224626777faef9efb9169da463653a583717cd3e
