### ISSUE TITLE
Release versioning

### ISSUE THREAD

**Issue by jakubjedelsky** [uber/vertica-python#50]
Hi,
fedora/epel package maintainer here. I have a small request - is it possible to tag releases of your code in one way? There are tags starting with "v" (eg. v0.3.5) and others without (eg. 0.3.6). 
Thanks!

**Comment by alexjikim** [comment]
not using a 'v' should be our standard. is this a request for going forward, or is this something you were hoping could be fixed for old released versions?

**Comment by jakubjedelsky** [comment]
It's definitely wish for going forward :)

**Comment by jberka** [comment]
@jakubjedelsky It looks like most of the last releases have been '0.x.x', so I'd plan on that being the versioning going forward. I'll add a comment to the setup file with that instruction next time I'm in there, too.
