### ISSUE TITLE
named arguments collide in substrings

### ISSUE THREAD

**Issue by arsturges** [uber/vertica-python#54]
If I use the named arguments `:s` and `:start_date`, then `:start_date` gets interpreted as `:s` and `tart_date`
```
"SELECT * FROM trips WHERE begintrip_lat > :s AND begintrip_at > :start_date LIMIT 4;", params={'s': 37, 'start_date': '2015-4-1'})
```
yields
```
'SELECT * FROM trips WHERE begintrip_lat > 37 AND begintrip_at > 37tart_date LIMIT 4;'
```

**Comment by jberka** [comment]
I see what's going on here, I'll fix it sometime in the next few days.

**Comment by jberka** [comment]
@alexjikim Fixed, can you close this?
