### ISSUE TITLE
vertica-python 0.4.1 errors on commit

### ISSUE THREAD

**Issue by vrbala** [uber/vertica-python#55]
*vertica-python version: 0.4.1*
*vertica version: 7.0.1-4*

Please look at the script below:

```python
import sys
sys.path.insert(0, '/path/to/vertica-python/vertica-python-master')
from vertica_python import connect

connection = connect({
        'host': 'host.vertica.com',
        'port': 5433,
        'user': 'user',
        'password': 'password',
        'database': 'vertica',
        'read_timeout': 86400
        }
    )

c = connection.cursor()
c.execute("COMMIT;")
result = c.fetchall()
connection.close()
print result
```
This is a contrived example but when I run this script, 

```
% python2.7 vertica-test.py
Message type: <class 'vertica_python.vertica.messages.backend_messages.notice_response.NoticeResponse'>
<vertica_python.vertica.messages.backend_messages.notice_response.NoticeResponse object at 0x7ffff0a06510>
Traceback (most recent call last):
  File "vertica-test.py", line 18, in <module>
    c.execute("COMMIT;")
  File "/path/to/vertica-python/vertica-python-master/vertica_python/vertica/cursor.py", line 73, in execute
    raise errors.QueryError("Unexpected message type", self.last_execution)
  File "/path/to/vertica-python/vertica-python-master/vertica_python/errors.py", line 77, in __init__
    error_response.error_message(), repr(self.one_line_sql()))
```

**Comment by zer0n** [comment]
Confirm the bug. I only tested with `select` query and ignored update queries.

**Comment by zer0n** [comment]
Fixed here: https://github.com/uber/vertica-python/commit/932fe36bfb8744d903332201a0981954029f8fa2

**Comment by zer0n** [comment]
@vrbala Can you try again?

**Comment by vrbala** [comment]
LGTM!

Tested with the script below - 

```python
import sys

sys.path.insert(0, '/home/vrbala/Downloads/vertica-python-932fe36bfb8744d903332201a0981954029f8fa2')

from vertica_python import connect

_CONNECTION_INFO = {
        'host': 'host.com',
        'port': 5433,
        'user': 'user',
        'password': 'password',
        'database': 'vertica',
        'read_timeout': 86400
        }

connection = connect(
    _CONNECTION_INFO
    )

c = connection.cursor()
c.execute("select version();")
result = c.fetchall()
print result

c.execute("update schema.bala_test set x_col = 2; ")
result = c.fetchall()
print result

c.execute("commit; ")
result = c.fetchall()
print result

c.execute("insert into schema.bala_test values (1, 1); ")
result = c.fetchall()
print result

c.execute("commit; ")
result = c.fetchall()
print result

c.execute("select * from schema.bala_test;")
result = c.fetchall()
print result

connection.close()
```

Thanks!

**Comment by vrbala** [comment]
@zer0n Is there a unit test suite for vertica-python?

**Comment by zer0n** [comment]
There's no test suite yet. Would you want to add?

**Comment by vrbala** [comment]
Yes, I would. But this needs running instances of vertica (may be multiple versions) to run the tests against. How to handle that?

**Comment by zer0n** [comment]
You can write tests leaving the connection info as parameters. If someone wants to test before commits, they can run: 
`python tests.py -host ... -user ...`

**Comment by vrbala** [comment]
I think I will work on it sometime. Will send a PR when I have something decent.

**Comment by zer0n** [comment]
Cool. We are reaching a point where  a test suit is needed.

**Comment by vrbala** [comment]
I think I had run the gun in the morning test. It seems we have serious issue with this release. See below - 

```python
import sys

sys.path.insert(0, '/home/vrbala/Downloads/vertica-python-932fe36bfb8744d903332201a0981954029f8fa2')

from vertica_python import connect

_CONNECTION_INFO = {
        'host': 'host.com',
        'port': 5433,
        'user': 'user',
        'password': 'password',
        'database': 'vertica',
        'read_timeout': 86400
        }

connection = connect(
    _CONNECTION_INFO
    )

c = connection.cursor()
c.execute("select version();")
result = c.fetchall()
print result

c.execute("select * from schema.bala_test;")
result = c.fetchall()
print result

c.execute("update schema.bala_test set x_col = 2; ")
result = c.fetchall()
print result

c.execute("commit; ")
result = c.fetchall()
print result

c.execute("insert into schema.bala_test values (1, 1); ")
result = c.fetchall()
print result

c.execute("commit; ")
result = c.fetchall()
print result

c.execute("select * from schema.bala_test;")
result = c.fetchall()
print result

connection.close()
```

When I run the script,

% python vertica-test.py
[[u'Vertica Analytic Database v7.1.1-11']]
[[Decimal('1'), u'1'], [Decimal('1'), u'1']]
[[2]]
[]
[[1]]
[]
[[Decimal('1'), u'1'], [Decimal('1'), u'1']]

The test table had 2 lines originally [[1,1],[1,1]]. If you notice even after the update and insert queries, nothing has changed in the tables. 

Feel free to comment if you think I am missing something.

**Comment by jberka** [comment]
What happens if you do ```c.execute("insert into schema.bala_test values (1, 1); COMMIT;")```?

The transaction may be getting discarded once the next execute starts.

Also, if anyone needs Vertica for testing, they have a free Community Edition.

**Comment by vrbala** [comment]
>>What happens if you do c.execute("insert into schema.bala_test values (1, 1); COMMIT;")?
This seems to work. Is this a changed behavior? 

I wouldn't expect a transaction to get discarded on subsequent executes on the same connection.

**Comment by jberka** [comment]
A few thoughts, in no particular order:

- Does vertica.log have anything useful in it? Sometimes the log is useful to see what Vertica last sent (vs. what the connector is processing).

- You may also want to put a print statement in the read_message function to dump every message. Your comment from a week or so ago that sometimes the message is a NoticeResponse (vs. a CommandComplete) has me thinking that perhaps the read_message() call in the iterator loop is getting something that isn't a data row and have problems processing it.

- The break on CommandComplete in the execute function may be causing problems; I understand what the function is trying to do, but I'm not sure DataRows should be treated the same as CommandComplete and ReadyForQuery (I believe additional messages can still come after a CommandComplete).

- Does putting the commit at the end of the statement work? I'm just curious.

- Could you try something like ```select x_col from schema.bala_test; select y_col from schema.bala_test;```? I'd love to see the output for that as well.

- The connection.commit() and connection.rollback() methods are probably broken too.

I may try and get Vertica working locally so I can poke around, too.

**Comment by vrbala** [comment]
Yes "COMMIT" at the end of the statements work.
OK, I am going to try these things but not sure when I can post my results. Will do so ASAP.

Is there a write up available somewhere that explains the vertica protocol over a raw socket? May help me pickup things a bit faster.

What is the path of vertica.log file?

**Comment by vrbala** [comment]
Looks like I have identified the cause of the issue. It is potentially due to the connection.reset_connection in cursor.execute method. This causes a connection reset after for every call to execute. Please correct me if I have misunderstood something.

**Comment by jberka** [comment]
That seems correct to me; because of the break in the iterator, self.last_execution is never getting unset anywhere (basically, the cursor is never cleaning up after itself). I think setting self.last_execution to None on CommandComplete or ReadyForQuery may work, but that change would require a bit of testing.

@vrbala The Vertica wire protocol is pretty close to the one used by Postgres, so this might be useful: http://www.postgresql.org/docs/9.0/static/protocol.html

**Comment by vrbala** [comment]
Cool, thanks! will take a look. I will also close this one and open a new issue to track this bug.
