### ISSUE TITLE
Inserts fail with Cannot commit: No transaction in progress

### ISSUE THREAD

**Issue by rjaiwal5139** [uber/vertica-python#62]
from vertica_python import connect

def get_connection():
    return connect({
            'host': '192.168.19.170',
            'port': 5433,
            'user': 'vertica_dba',
            'password': 'password',
            'database': 'ceilometer'
    })

with get_connection() as conn:
        insert_stmt = "INSERT INTO %s..."
        cur = conn.cursor()
        cur.execute(insert_stmt)

fails with the following stack trace:

  raise errors.QueryError("Unexpected message type", self.last_execution)
vertica_python.errors.QueryError: Unexpected message type, SQL: 'commit'

**Comment by Bennyelg** [comment]
Same Issue over here.

**Comment by alexjikim** [comment]
will take a look at this and other issues starting with version 4.x today

**Comment by jberka** [comment]
What version are you using, and can you paste the full insert statement? This is working for me on the latest master.

```
from vertica_python import connect


def get_connection():
    return connect({
        'host': '127.0.0.1',
        'port': 5433,
        'user': 'dbadmin',
        'password': 'password',
        'database': 'test'
    })


with get_connection() as conn:
    c = conn.cursor()

    c.execute("SELECT VERSION();")
    result = c.fetchall()
    print result

    c.execute("INSERT INTO test_table VALUES (2, 'string2', 3); COMMIT;")

    c.execute("SELECT * FROM test_table;")
    result = c.fetchall()
    print result
```

Result:
```
[[u'Vertica Analytic Database v7.1.1-0']]
[[1, u'olaf', 2], [2, u'string2', 3]]
```

**Comment by jberka** [comment]
@rjaiwal5139 @Bennyelg See above ^

**Comment by Bennyelg** [comment]
Thanks! I was 2 versions back in some strange reason :/

**Comment by rjaiwal5139** [comment]
I am on vertica 7.1.1-0 and this is my insert statement -

insert_stmt = "INSERT INTO %s (meter_id, meter_name, meter_type,
meter_unit) " \
                  "VALUES (HEX_TO_BINARY('%s'), '%s', '%s', '%s'); COMMIT;"
%\
                  (table_name, meter_id, name, _type, unit)


still get the error - vertica_python.errors.QueryError: Unexpected message
type, SQL: 'commit'

**Comment by jberka** [comment]
Interesting. My guess would be that the hex getting adding to the query is causing something to break; I don't think use of the HEX_TO_BINARY() function has come up before.

Could you provide a sample set of values that cause the error? The table schema for the destination table would also be helpful.

**Comment by rjaiwal5139** [comment]
'INSERT INTO meter (meter_id, meter_name, meter_type, meter_unit) VALUES (\\'6310387d8bfdac272678bd54c691e7b1460b6f45\\'), \\'hello-world\\', \\'gauge\\', \\'hw\\'); COMMIT;'

Following is the schema - 

| column_name                                                                                                                     | data_type                                                                                                                       |
+---------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| meter_id                                                                                                                        | binary(20)                                                                                                                      |
| meter_name                                                                                                                      | varchar(255)                                                                                                                    |
| meter_type                                                                                                                      | varchar(255)                                                                                                                    |
| meter_unit                                                                                                                      | varchar(255)                                                                                                                    |
+-------------------------------

**Comment by jberka** [comment]
I'm still having trouble reproducing this. Maybe the quote escaping is causing problems?

Using a test table with a BINARY(20) column:
```
c.execute("INSERT INTO bintest_table VALUES (HEX_TO_BINARY('6310387d8bfdac272678bd54c691e7b1460b6f45'), 'test'); COMMIT;")

c.execute("SELECT * FROM bintest_table;")
result = c.fetchall()
print result
```

Result
```
[[u'Vertica Analytic Database v7.1.1-0']]
[["c\\0208}\\213\\375\\254'&x\\275T\\306\\221\\347\\261F\\013oE", u'test']]
```

**Comment by jberka** [comment]
Are you using the latest version of the package?

**Comment by rjaiwal5139** [comment]
I was using 0.4.1

**Comment by rjaiwal5139** [comment]
i got 0.4.3, let me try with that

**Comment by Bennyelg** [comment]
Update to 0.4.5 it's work perfect there, anyone can confirm and close this thread?

**Comment by alexjikim** [comment]
going to close as it sounds like its been fixed.
