### ISSUE TITLE
vertica_python.errors.ConnectionError: unsupported authentication method: 9

### ISSUE THREAD

**Issue by mverrilli** [uber/vertica-python#68]
I'm not sure if a setting changed on the cluster I connect to or not, however I started getting this error out of the blue, nothing has changed on the code side. It happens on connect using: 

     { 'host': 'vertica', 'port': 5433, 'user': 'someuser', 'password': 'somepassword', 'database': 'MYDB'}

Any ideas where to look or what this is about?

**Comment by mverrilli** [comment]
Ok I figured it out. The password expired for this user.  Probably best to handle this a better way.

**Comment by alexjikim** [comment]
Couldn't find info on the actual error code being sent by vertica, but trying to be more helpful with this dumb error check:

1f8c62a5d9fdcf267dbe25a1c54c55b1e6696559
