### ISSUE TITLE
Cursor.nextset support?

### ISSUE THREAD

**Issue by davidhewitt** [uber/vertica-python#74]
Hey there,

We've been using vertica-python to run SQL queries containing multiple insert statements (into temp tables) followed by a select statement at the end to join all the temp table data and pull it out, e.g.

    INSERT INTO temp_table (...) SELECT ... ;
    INSERT INTO temp_table (...) SELECT ... ;
    INSERT INTO temp_table (...) SELECT ... ;
    SELECT ... from temp_table WHERE ...;

Somewhere around this commit I think vertica-python's behaviour changed to return the result of the first statement rather than the last: https://github.com/uber/vertica-python/commit/102f681c7364802e12e17e8d9895cde3faba1e5d. This isn't ideal because that means our jobs are returning the number of rows inserted to the temp table rather than the data we actually want.

As a result we're stuck on vertica-python 0.3.6 :(

I thought that I could make a workaround involving the [Cursor.nextset() function] (https://www.python.org/dev/peps/pep-0249/#nextset) but then I saw it's not implemented. Actually, in that commit above it seems the placeholder was also removed.

Any chance we can work together to either restore the previous behaviour or implement the .nextset function?

This is an awesome library btw :)

Cheers
David

**Comment by alexjikim** [comment]
Im not sure i understand whats happening. is select returning the wrong thing? row_count?

**Comment by Bennyelg** [comment]
This is what happening i guess : 
"""Somewhere around this commit I think vertica-python's behaviour changed to return the result of the first statement rather than the last:"""

**Comment by davidhewitt** [comment]
Hey,

I think this is the way to repro (don't have my laptop with me this weekend, so this is from memory). Try running something like this:

    conn = connect(...)
    c = conn.cursor()
    c.execute("select 1; select 2;")
    print c.fetchall()

From what I'm getting, on vertica-python 0.3.6 the returned result will be 2, and on vertica-python 0.5 the returned result will be 1.

The .nextset() function from the python DB Api looks like the way I would need to go to get the result "2" in the current 0.5 behaviour. Hence the thread title :)

Cheers

**Comment by alexjikim** [comment]
nextset() was added as a part of 0.5.2. check the readme for details on how it works. hope this resolves your issue.
