### ISSUE TITLE
Bug : cursor.description[idx].name returns only function name when we use an aggregate function on a column

### ISSUE THREAD

**Issue by pandyajay10** [uber/vertica-python#76]
when using cursor.description.name on select sum(a), sum(b) from temp_table we get name = "sum" for both columns while the name should also include attribute ( sum(a) ) to make name unique. We are facing an issue due to this bug.

**Comment by mverrilli** [comment]
Someone can correct me if I am wrong, but I believe this is a Vertica thing when you do not alias your columns, not a vertica-python thing. Just alias them and it should be fine.  select sum(a) as sum_a, sum(b) as sum_b from temp_table. Or if you really want them to be the full formula, you could use quoted identifiers.  select sum(a) as "sum(a)", sum(b) as "sum(b)" from temp_table

**Comment by pandyajay10** [comment]
I am using this library to for a vertica UI hence trying to support all types of generic queries.  Thats why I know aliasing would work but it would be better if there was a generic solution.

**Comment by mverrilli** [comment]
Well, vertica_python would only return what Vertica hands it.  For example, if you run your query in vsql, it will also tell you the column names are both "sum".  To do what you are suggesting in vertica_python, they would have to parse the SQL and while I'm not a project contributor, I would guess that this is out of scope. 

I think you'll have to accept that column names may not be unique, and reference by position.  Or maybe dedup them by adding a sequence on the dups. Just some ideas.

**Comment by alexjikim** [comment]
As @mverrilli mentioned, vertica_python is simply returning the column names provided by vertica. Parsing the sql query to try to change this feels wrong and error prone, so i think ill leave this as is. I hope you are able to use aliasing to fix the issues you are running into.

**Comment by pandyajay10** [comment]
Yes, I used deduping of column names and it worked. Thanks for helping.
