### ISSUE TITLE
python3.x support

### ISSUE THREAD

**Issue by gled-rs** [uber/vertica-python#85]
A patch is being made to support python3 by the debian guys ( attached to this issue ).

It may be great to integrate it in the source or in a branch for the nondebian users ?
[python3-vertica-patch.txt](https://github.com/uber/vertica-python/files/39626/python3-vertica-patch.txt)

**Comment by alexjikim** [comment]
nice. i think a branch would be great. we can adopt a new tag format for the python 3.x releases.
ill clean up the current branch situation so its easier to find/use.

**Comment by gled-rs** [comment]
Sounds good, let me know if you need help !

**Comment by alexjikim** [comment]
created a new branch with this patch applied; python3-master
(dont have an python 3 environment to test it though)

**Comment by FredrikAppelros** [comment]
I think this issue should be reopened as the code in the `python3-master` branch does not work in either Python 3, nor Python 2. It's just broken.

**Comment by gled-rs** [comment]
indeed the patch provided by debian is not enough on python-vertica 0.5.5 ( it's the debian maintainer who made it ) to fix python3.2+ compat.

One of the issue is here: http://bugs.python.org/issue10783 . in python3/3.1 pack was silently converting strings to UTF-8 bytes, and not anymore since python3.2 ( fix in progress in the patch attached ).

But patching that and a few errors message in catch blocks leaves us with a vertica connection being closed even though the credentials are valid.

[python3.2-wip.patch.txt](https://github.com/uber/vertica-python/files/61941/python3.2-wip.patch.txt)

I unfortunately don't have enough time to fix it ASAP, $dailyjob first, but working on it on my spare time though...

**Comment by nchammas** [comment]
So is the current plan to support Python 3 on its own branch, as opposed to within the same codebase?

Also, if the library as it stands on `master` doesn't work with Python 3, then this issue should be reopened. Unless, of course, Python 3 support is not a goal.

**Comment by jbfavre** [comment]
Hello. I'm the debian maintainer for python-vertica.
Indeed, patch is broken, and I'm really sorry for that :-/

I'm trying to fix it for python-vertica 0.5.6, but got confused with master & python3-master differences.
I'd also like to have compatible code in master instead of separated branches.
